### ISSUE TITLE
get Cookies

### ISSUE THREAD

**Issue by ZeroneDoo** [shobhitexe/insta-spider#1]
how to get the cookies?

**Comment by shobhitexe** [comment]
To retrieve cookies from Instagram, follow these steps:

1. Open Instagram in your preferred web browser.
2. Open the developer tools of your browser. In Chrome or any other browser, you can usually do this by right-clicking anywhere on the page and selecting "Inspect" or "Inspect Element."
3. In the developer tools panel, navigate to the "Network" tab.
4. Refresh the Instagram page to capture the network activity.
5. Look for a fetch request (or any other type of network request) in the list of network activities. These requests are typically labeled with names like "fetch," "xhr," or "api."
6. Click on the fetch request to inspect its details.
7. In the request headers section, you should find the "Cookies" header. This header contains the cookies associated with your Instagram session.

![image](https://github.com/shobhitexe/insta-spider/assets/29349136/20677a81-ad1b-4972-947b-a30a6b593190)

**Comment by shobhitexe** [comment]
To retrieve cookies from Instagram, follow these steps:

Open Instagram in your preferred web browser.
Open the developer tools of your browser. In Chrome or any other browser, you can usually do this by right-clicking anywhere on the page and selecting "Inspect" or "Inspect Element."
In the developer tools panel, navigate to the "Network" tab.
Refresh the Instagram page to capture the network activity.
Look for a fetch request (or any other type of network request) in the list of network activities. These requests are typically labeled with names like "fetch," "xhr," or "api."
Click on the fetch request to inspect its details.
In the request headers section, you should find the "Cookies" header. This header contains the cookies associated with your Instagram session.

![image](https://github.com/shobhitexe/insta-spider/assets/29349136/465e21cd-1010-41b9-87bc-b2d8d7b80b8c)

**Comment by ZeroneDoo** [comment]
ohhh okok, thank you so much
